name: Test

on:
  push:
    paths-ignore:
    - '*.mkd'
    - 'LICENSE'
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # toolchain 1.46 cannot parse edition 2021, libc requires MSRV 1.63
        rust_toolchain: [nightly, stable, 1.63]
        # doesn't compile on Apple Silicon (issue #20)
        os: [ubuntu-latest, windows-latest, macos-13]
        flags: ["", "--no-default-features", "--release", "--release --no-default-features"]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.rust_toolchain }}
            profile: minimal
            default: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=Cargo.toml ${{ matrix.flags }} -- --nocapture

  bench:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            profile: minimal
            default: true
      - uses: actions-rs/cargo@v1
        with:
          command: bench
